# docker-compose exec web python manage.py migrate --no-input
version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn dj_renew.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=struccle
      - POSTGRES_PASSWORD=struccle
      - POSTGRES_DB=struccle_db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: